name = "udrive-queue-consumer"
main = "src/queue-consumer.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
queue = "udrive-delete-queue"
max_batch_size = 1
max_batch_timeout = 30

[env.production]
vars = { }
