name = "udrive-queue-consumer"
main = "dist/queue-consumer.js"
compatibility_date = "2026-06-07"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
queue = "udrive-delete-queue"
max_batch_size = 1
max_batch_timeout = 30

[[d1_databases]]
binding = "DB"
database_name = "udrive"

[env.production]
vars = { }
