name = "udrive-queue-consumer"
main = "dist/queue-consumer-worker.js"
compatibility_date = "2026-06-07"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[queues.producers]]
binding = "DELETE_QUEUE"
queue = "udrive-delete-queue"

[[queues.consumers]]
queue = "udrive-delete-queue"
max_batch_size = 1
max_batch_timeout = 30

[[d1_databases]]
binding = "DB"
database_name = "udrive"

[env.production]
vars = { }
